import CardScan

...
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
  ...
  ScanViewController.configure(apiKey: "stripe_publishable_key")
  ...
}
